name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install github cli
        run: brew install gh
      - name: Install hpar
        run: |
          BiocManager::install('lgatto/hpar')
        shell: Rscript {0}
      - name: Check HPA versions
        run: |
          hpar_version <- hpar::getHpaVersion()
          hpa_version <- hpar:::getHpaRelease()['version']
          if (hpar_version == hpa_version) print("HELLO!")
        shell: Rscript {0}