name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - uses: actions/checkout@v2
      - name: Install hpar
        run:  Rscript -e "BiocManager::install('lgatto/hpar')"
      - name: Check HPA versions
        run: |
          hpar_version <- hpar::getHpaVersion()
          hpa_version <- hpar:::getHpaRelease()['version']
          if (hpar_version == hpa_version) cat(date(), sep = "\n", file = "version_tracker", append = FALSE)
          dir()
        shell: Rscript {0}
      - uses: marceloprado/has-changed-path@v1
        id: hpar-version
        with:
          paths: version_tracker
      - name: Create Issue From File
        if: steps.hpar-version.outputs.changed == 'true'
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: hpar version
          content-filepath: version_tracker
