name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: GitHub Action for Homebrew
        uses: artemnovichkov/action-homebrew@0.1.0
        args: install gh
      - name: Install hpar
        run:  Rscript -e "BiocManager::install('lgatto/hpar')"
      - name: Check HPA versions
        run: |
          hpar_version <- hpar::getHpaVersion()
          hpa_version <- hpar:::getHpaRelease()['version']
          if (hpar_version == hpa_version) print("HELLO!")
        shell: Rscript {0}