name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install hpar
        run:  Rscript -e "BiocManager::install('lgatto/hpar')"
      - name: Check HPA release
        run: |
          hpaRelease <- hpar:::getHpaRelease()
          save(hpaRelease, file = "./hpaRelease")
        shell: Rscript {0}
      - name: Has hpaRelease.rda changed
        uses: MarceloPrado/has-changed-path@v1.0
        id: hpaRelease
        with:
          paths: hpaRelease
      - name: Create Issue From File
        if: steps.hpaRelease.outputs.changed == 'true'
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: New HPA version
          content-filepath: hpaRelease
