name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: Install cli interface to GitHub
        run: sudo apt install cligh
      - name: Install hpar
        run:  BiocManager::install('lgatto/hpar')
      - name: Check HPA versions
        run: |
          hpar_version <- hpar::getHpaVersion()
          hpa_version <- hpar:::getHpaRelease()['version']
          if (hpar_version == hpa_version) print("HELLO!")
        shell: Rscript {0}