name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: Install hpar
        run: |
          BiocManager::install('lgatto/hpar')
          BiocManager::install('rpremraj/mailR')
        shell: Rscript {0}
      - name: Check HPA versions
        run: |
          hpar_version <- hpar::getHpaVersion()
          hpa_version <- hpar:::getHpaRelease()['version']
          if (hpar_version == hpa_version) {
             mailR::send.mail(from = "laurent.gatto@gmail.com",
                              to = "laurent.gatto@gmail.com",
                              subject = "GHA hpar version",
                              smtp = list(host.name = "aspmx.l.google.com", port = 25),
                              send = TRUE)
           }
        shell: Rscript {0}