name: check_hpar_version
on: [push]

jobs:
  hpar_versions:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: Install hpar
        run:  Rscript -e "BiocManager::install('lgatto/hpar')"
      - name: Check HPA versions
        run: |
          hpar_version <- hpar::getHpaVersion()
          hpa_version <- hpar:::getHpaRelease()['version']
          if (hpar_version == hpa_version) writeLines("HELLO", con = "msg.md")
        shell: Rscript {0}
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: hpar version
          content-filepath: msg.md
